import type { Metadata } from "next";
import {
	Source_Serif_4,
	Source_Sans_3,
	Geist,
	Geist_Mono,
	IBM_Plex_Sans,
	Crimson_Pro,
	EB_Garamond,
} from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import Footer1 from "./components/Footer1";
import { getDictionary } from "./lib/language/dictionary";
import { getLanguage } from "./lib/language/getLanguage";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const naslov = Source_Serif_4({
	variable: "--font-naslov",
	subsets: ["cyrillic", "latin"],
});
const text = Source_Sans_3({
	variable: "--font-text",
	subsets: ["cyrillic", "latin"],
});
const CrimsonText = Crimson_Pro({
	variable: "--font-hey",
	subsets: ["latin"],
});

const EBGaramond = EB_Garamond({
	variable: "--font-eb-garamond",
	subsets: ["cyrillic", "latin"],
});
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const ibmPlex = IBM_Plex_Sans({
	variable: "--font-ibm-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const lang = await getLanguage();
	const dict = await getDictionary(lang);
	return (
		<html
			lang={lang === "en" ? "en" : "sr"}
			className={`${geistSans.variable} ${geistMono.variable} ${ibmPlex.variable} h-full ${EBGaramond.variable} ${naslov.variable} ${text.variable} antialiased`}
		>
			<body className="flex flex-col min-h-full">
				<Nav />
				{children}
				<Footer1
					content={dict.footer}
					lang={lang}
				/>
			</body>
		</html>
	);
}
